### Variables
@goshuin_service_url = http://localhost:8083

### Login with the test account (to get token for POST)
POST http://localhost:8081/api/v1/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "Password123!"
}

> {%
    if (response.status === 200 && response.body) {
        client.global.set("access_token", response.body.accessToken);
        client.global.set("refresh_token", response.body.refreshToken);
    } else {
        client.log("Request failed or returned empty body. Status: " + response.status);
    }
%}

### Get all goshuins (Public)
GET {{goshuin_service_url}}/api/v1/goshuin?limit=20&sort=createdAt
Accept: application/json