spring:
  profiles:
    active: local
  application:
    name: auth-service
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        default_schema: auth_schema
  security:
    oauth2:
      client:
        registration:
          google:
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}${GOOGLE_REDIRECT_URI:/login/oauth2/code/{registrationId}}"
            scope:
              - openid
              - email
              - profile
        provider:
          google:
            issuer-uri: https://accounts.google.com
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS auth_schema;
  liquibase:
    change-log: classpath:db/changelog/auth-service/db.changelog-master.yaml
    enabled: false
    default-schema: auth_schema
    liquibase-schema: auth_schema
  cloud:
    openfeign:
      client:
        config:
          profile-service:
            url: https://${PROFILE_SERVICE_URL}
            connectTimeout: 2000
            readTimeout: 3000

server:
  port: ${PORT:8081}
  forward-headers-strategy: framework

management:
  endpoints:
    web:
      exposure:
        include: health