spring:
  profiles:
    active: local
  application:
    name: profile-service
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        default_schema: profile_schema
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS profile_schema;
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
    default-schema: profile_schema
    liquibase-schema: profile_schema

server:
  port: ${PORT:8082}

management:
  endpoints:
    web:
      exposure:
        include: health