spring:
  profiles:
    active: local
  application:
    name: goshuin-service
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        default_schema: goshuin_schema
        default_batch_fetch_size: 50
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS goshuin_schema;
  liquibase:
    change-log: classpath:db/changelog/goshuin-service/db.changelog-master.yaml
    enabled: false
    default-schema: goshuin_schema
    liquibase-schema: goshuin_schema
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
      client:
        config:
          profile-service:
            url: ${PROFILE_SERVICE_URL:http://localhost:8082}
            connectTimeout: 2000
            readTimeout: 3000

gcp:
  storage:
    bucket-name: ${GCP_STORAGE_BUCKET_NAME}
    credentials-json: ${GCP_STORAGE_CREDENTIALS_JSON:}
    avatar:
      max-size-bytes: 5242880 # 5MB
      allowed-content-types:
        - image/jpeg
        - image/png
        - image/webp

server:
  port: ${PORT:8083}

management:
  endpoints:
    web:
      exposure:
        include: health