FROM maptiler/tileserver-gl:latest

# Copy the mbtiles file to the /data directory
# We rename it to japan.mbtiles to match the configuration provided via environment variables
COPY osm-2020-02-10-v3.11_asia_japan.mbtiles /data/japan.mbtiles
